name: testing_model

on: 
  workflow_dispatch:

env:
  test_model_name: bert-base-uncased
  test_sku_type: cpu
  test_trigger_next_model: true
  test_queue: test-bert_model
  test_set: huggingface-all
  test_keep_looping: false

jobs:
  deploy-model-job:
    runs-on: ubuntu-latest
    steps:
    - name: check-out-repo-step
      uses: actions/checkout@v2
    - name: azure-login-step
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: pip-install-azure-ai-ml
      run: pip install azure-ai-ml
    - name: pip-install-azureml-core
      run: pip install azureml-core
    - name: pip-install-azureml-sdk
      run: pip install azureml-sdk
    - name: deploy-model-step
      id: deploy-model-step
      run: python testing_bart.py
      working-directory: tests/src
