name: Update README with Python Output

on:
  workflow_dispatch:
    #branches:
      #- main  # Adjust this to your default branch

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify the desired Python version
    - name: pip-install-pandas
      run: pip install pandas
    - name: pip-install-simplejson
      run: pip install simplejson
    - name: pip-install-pyyaml
      run: pip install pyyaml
    - name: Generate Output
      run: python update-readme.py > table.md
    - name: Update README
      run: |
         cat table.md > test.md
         git add table.md
         git commit -am "Update readme with table"
         git push
      
    # - name: Commit and push changes
    #   run: |
    #      git add table.md
    #      git config --local user.email "swathipriyarv23@gmail.com"
    #      git config --local user.name "Swathi23345"
    #      git commit -am "Update readme with table"
    #      git push
         
         
   


   
