on: workflow_dispatch

jobs:
  setup_azure_ml_env:
    runs-on: ubuntu-latest
    env:
        GIT_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  
        with:
          lfs: true
          repository: Konjarla-Vindya/son-azureml-oss-models
          ref: main
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r autoenv_requirements.txt

      - name: Run Python Script to Setup Azure ML Environment
        run: python automate-create-env.py  

      
