on: workflow_dispatch

jobs:
  setup_azure_ml_env:
    runs-on: ubuntu-latest
    env:
        GIT_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  
        with:
          lfs: true
          repository: Konjarla-Vindya/son-azureml-oss-models
          ref: main
          token: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r autoenv_requirements.txt

      - name: Run Python Script to Setup Azure ML Environment
        run: python automate_create_env.py 
      - name: Add Generated File
        run: |
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER_NAME }}"
          git pull origin main
          git add testing.md
          # Attempt to commit changes and handle errors
          set +e
          git commit -m "Add testing.md"
          commit_status=$?
          set -e
          if [ $commit_status -eq 0 ]; then
            git push origin main  # Added 'origin main' to be explicit about where to push
          else
            echo "No changes to commit or there was an error. Skipping commit and push."
          fi

      
