name: Azure-ML-Model-FT-Deployment

on:
  workflow_dispatch:

jobs:
  deploy_and_infer:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r autoenv_requirements.txt

      - name: Fetch Latest Model Version
        id: fetch_model
        run: |
          python fetch_latest_model_version.py --config_file son-azureml-oss-models/config.json

      - name: Modify JSON Configuration
        run: |
          model_name=$(jq -r .model_name config.json)
          latest_model_version=$(cat latest_model_version.txt)  
          jq --argjson latest_model_version "$latest_model_version" '.model_version = $latest_model_version' config.json > modified_config.json
          mv modified_config.json config.json

      - name: Run Python Script to Deploy and Infer
        run: python deploy_and_infer.py

      - name: Add Generated Files
        run: |
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER_NAME }}"
          git pull origin main
          git add .  # This assumes deploy_and_infer.py generates files you want to commit
          set +e
          git commit -m "Add generated files"
          commit_status=$?
          set -e
          if [ $commit_status -eq 0 ]; then
            git push origin main
          else
            echo "No changes to commit or there was an error. Skipping commit and push."
          fi
