name: Check Keywords Workflow

on:
  workflow_dispatch

jobs:
  check-keywords:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Read Keywords from CSV
      id: read-csv
      run: |
        KEYWORDS=($(cat tests/config/modellist.csv))
        echo "KEYWORDS=${KEYWORDS[*]}" >> $GITHUB_ENV

    - name: Check Keywords
      run: |
        FILE_PATH="dummy.txt"
        FOUND_KEYWORDS=()

        for keyword in "${KEYWORDS[@]}"; do
          if grep -q "$keyword" "$FILE_PATH"; then
            echo "Keyword '$keyword' found in $FILE_PATH"
            FOUND_KEYWORDS+=("$keyword")
          fi
        done

        if [ ${#FOUND_KEYWORDS[@]} -eq 0 ]; then
          echo "No keyword found."
        else
          echo "Keywords check passed."
          echo "Found keywords: ${FOUND_KEYWORDS[@]}"
        fi

        echo "All keywords: ${KEYWORDS[@]}"


