name: Check Keywords Workflow

on:
   workflow_dispatch
  # pull_request:
  #   paths:
  #     - 'dummy.txt'

jobs:
  check-keywords:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check Keywords
      run: |
        KEYWORDS=("example" "important")
        FILE_PATH="dummy.txt"

        for keyword in "${KEYWORDS[@]}"; do
          if grep -q "$keyword" "$FILE_PATH"; then
            echo "Keyword '$keyword' found in $FILE_PATH"
          fi
        done

        echo "Keywords check passed."
