name: Check Keywords Workflow

on:
   workflow_dispatch

jobs:
  check-keywords:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Read Keywords from CSV
      id: read-csv
      run: |
        KEYWORDS=($(cat tests/config/modellist.csv))
        echo "KEYWORDS=${KEYWORDS[*]}" >> $GITHUB_ENV

    - name: Check Keywords
      run: |
        FILE_PATH="dummy.txt"

        for keyword in "${KEYWORDS[@]}"; do
          if grep -q "$keyword" "$FILE_PATH"; then
            echo "Keyword '$keyword' found in $FILE_PATH"
          fi
        done

        echo "Keywords check passed."
