name: Latest_Model

on:
  workflow_dispatch

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    env:
       token: ${{ secrets.WORKFLOW_TOKEN }}
      # GIT_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
        # # ref: main
            lfs: true
            repository: Konjarla-Vindya/son-azureml-oss-models
            branch: main
        # #     git config global init.defaultBranch main
            token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 # Use the desired Python version
      - name: pip-install--pandas 
        run: pip install pandas 
      - name: pip-install--huggingface_hub 
        run: pip install huggingface_hub 
      

      - name: Run Python Script
        run: python automate_list.py

      - name: Add Generated File
        run: |
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER_NAME }}"
          git pull origin main
          cd tests/config
          git add lastweek_updated_models_min10_downloads.csv    
          # Attempt to commit changes and handle errors
          set +e
          git commit -m "lastweek_updated_models_min10_downloads.csv"
          commit_status=$?
          set -e
          if [ $commit_status -eq 0 ]; then
            git push
          else
            echo "No changes to commit or there was an error. Skipping commit and push."
          fi
        
