name: Latest_Model

on:
  workflow_dispatch

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Use the desired Python version

      - name: Run Python Script
        run: automate_list.py
