on: workflow_dispatch
jobs:
  testing:
    runs-on: ubuntu-latest

    env:
        GIT_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        with:
        # ref: main
        lfs: true
        repository: Konjarla-Vindya/son-azureml-oss-models
        branh: main
      #     git config global init.defaultBranch main
        token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.10
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r runs_requirements.txt
      - name: Run Python Script
        run: |
          python testing.py
      - name: Add Generated File
        run: |
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER_NAME }}"
          git pull origin main
          git add testing.md          
          # Attempt to commit changes and handle errors
          set +e
          git commit -m "Add testing.md"
          commit_status=$?
          set -e
          if [ $commit_status -eq 0 ]; then
            git push
          else
            echo "No changes to commit or there was an error. Skipping commit and push."
          fi
