name: Trigger-model

on: 
  workflow_dispatch:

jobs:
  deploy-model-job:
    runs-on: ubuntu-latest

    steps:
    - name: check-out-repo-step
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Use the appropriate Python version

    - name: Install dependencies
      run: |
        pip install azure-ai-ml
        pip install azureml-core
        pip install azureml-mlflow==1.53.0
        pip install transformers
        pip install transformers[torch]
        pip install torchvision 
        pip install mlflow
        pip install python-box 
        pip install sacremoses
        pip install sentencepiece
        pip install fugashi[unidic-lite]

    - name: deploy-model-step
      id: deploy-model-step
      run: python Trigger-model.py

    - name: Display Python script output
      run: echo "Script output: ${{ steps.deploy-model-step.outputs.stdout }}"
