name: Your Python Script

on:
  push:
    branches:
      - main  # Or specify your branch

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Choose the Python version you need

    - name: Run Python script
      run: |
        python Trigger-model.py > output.log  # Redirect output to a log file
        cat output.log  # Display the log content

    - name: Upload log file
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: output.log
