name: Automate Azure ML Environment Creation

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-automate-creation-env]

jobs:
  setup_azure_ml_env:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: check-out-repo-step
      uses: actions/checkout@v2
      
    - name: azure-login-step
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.9
      
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r autoenv_requirements.txt

    - name: Run Python Script to Setup Azure ML Environment
      run: python automate_create_env.py 
      
    - name: Add Generated File
      run: |
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER_NAME }}"
          git pull origin main
          git add conda.yaml  # assuming this is the generated file
          set +e
          git commit -m "Automatically update conda.yaml"
          commit_status=$?
          set -e
          if [ $commit_status -eq 0 ]; then
            git push origin main
          else
            echo "No changes to commit or there was an error. Skipping commit and push."
          fi

