name: Trigger Automate-creation-env.yml in Repo A
on:
  repository_dispatch:
    types: [trigger-automate-creation-env]

jobs:
  setup_azure_ml_env:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo A
        uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r autoenv_requirements.txt
      - name: Run Python Script to Setup Azure ML Environment
        run: python automate_create_env.py
      - name: Add Generated File
        run: |
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER_NAME }}"
          git pull origin main
          git add testing.md
          set +e
          git commit -m "Add testing.md"
          commit_status=$?
          set -e
          if [ $commit_status -eq 0 ]; then
            git push origin main
          else
            echo "No changes to commit or there was an error. Skipping commit and push."
          fi
