name: TRIGGER_TESTS

on: 
  workflow_dispatch:
    inputs:
      test_queue:
        description: 'Test set to run'
        default: huggingface-all

jobs:
  start-tests-job:
    runs-on: ubuntu-latest
    steps:
    - name: check-out-repo-step
      uses: actions/checkout@v2
    # - name: Print Model Names
    #     run: |
    #       models_json=$(cat models.json)
    #       models_list=$(echo "$models_json" | jq -r '.models[]')
    #       echo "Model Names: $models_list"
    - name: start-tests-step
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ${{ inputs.test_queue }}
        pwd
        ls -1
        for file in `ls -1`  
        do  
          # # echo "Triggering workflow for $file"
          # models_json=$(cat file.json)
          # models_list=$(echo "$models_json" | jq -r '.models[]')
          # echo "Model Names: $models_list"
          # gh workflow run "$file.yml" -R Konjarla-Vindya/son-azureml-oss-models -F model_name="$file"
          gh workflow run `cat $file | head -n 1`
          # gh workflow run `cat $file | head -4 | tail -1 | sed 's/,//' | sed 's/"//g'`
          gh working-directory: github/workflows
        done    
      working-directory: tests/config/queue
