name: abc

on: 
  workflow_dispatch:

env:
  test_model_name: abc

jobs:
  deploy-model-job:
    runs-on: ubuntu-latest
    steps:
    - name: check-out-repo-step
      uses: actions/checkout@v2
    - name: azure-login-step
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: pip-install-azure-ai-ml
      run: pip install azure-ai-ml
    - name: pip-install-python-box
      run: pip install python-box 
    - name: deploy-model-step
      id: deploy-model-step
      run: python try_model.py
      working-directory: automation/tests/setup
    - name: Commit files
      id: commit
      run: | 
        git config user.email "${{ secrets.USER_EMAIL }}"           
        git config user.name "${{ secrets.USER_NAME }}"
        git add --all
        git commit -m --all          
        git push
    - name: trigger-next-model-step
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ env.test_trigger_next_model == 'true' && steps.deploy-model-step.outputs.NEXT_MODEL != '' && (success() || failure())}}
      run: gh workflow run ${{ steps.deploy-model-step.outputs.NEXT_MODEL }} --ref ${{ github.ref_name }}